* Makefile Template
:LOGBOOK:
- Refiled on [2020-01-30 Thu 16:42]
:END:
Borrowed from [[https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html][Marmelab]].
    #+begin_src makefile
      .PHONY: help
      help: ## Display this help section
          @awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z0-9_-]+:.*?## / {printf "\033[36m%-38s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
      .DEFAULT_GOAL := help
    #+end_src
