#+title: Sway
#+index: Linux!Sway
#+property: header-args :tangle (if (eq system-type 'gnu/linux) "~/.config/sway/config" "no")

* Intro

#+begin_src conf
  set $mod Mod4
  set $term kitty
#+end_src

* Background

#+begin_src conf
  # output * bg ~/Downloads/desktop.jpg fill
#+end_src

* Keyboard

#+begin_src conf
  input * {
          natural_scroll enabled
          xkb_layout "us,us"
          xkb_variant "colemak,,"
          xkb_options "ctrl:nocaps"
  }
#+end_src

* Basic bindings

#+begin_src conf
  for_window [app_id="^launcher$"] floating enable, sticky enable, resize set 30 ppt 60 ppt, border pixel 10
  set $menu exec $term --class=launcher -e sway-launcher-desktop
  bindsym $mod+space exec $menu
  bindsym $mod+Return exec $term
  bindsym $mod+Shift+q kill
#+end_src

* Floating windows
      # Drag floating windows by holding down $mod and left mouse button.
      # Resize them with right mouse button + $mod.
      # Despite the name, also works for non-floating windows.
      # Change normal to inverse to use left mouse button for resizing and right
      # mouse button for dragging.

#+begin_src conf
      floating_modifier $mod normal
#+end_src

* Reload config

#+begin_src conf
  bindsym $mod+Shift+c reload
#+end_src

* Screenshots

#+begin_src conf
      bindsym $mod+x exec grim ~/Downloads/$(date +%Y-%m-%d_%H-%m-%s).png
      bindsym $mod+Shift+x exec grim -g "$(slurp)" ~/Downloads/$(date +%Y-%m-%d_%H-%m-%s).png
#+end_src

* Log out

#+begin_src conf
  bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -b 'Yes, exit sway' 'swaymsg exit'
#+end_src

* Moving around

#+begin_src conf
  set $left b
  set $right f
  set $up p
  set $down n
#+end_src

Move focus around

#+begin_src conf
  bindsym $mod+$left focus left
  bindsym $mod+$down focus down
  bindsym $mod+$up focus up
  bindsym $mod+$right focus right

  bindsym $mod+Left focus left
  bindsym $mod+Down focus down
  bindsym $mod+Up focus up
  bindsym $mod+Right focus right
#+end_src

Move the focused window with the same, but add Shift

#+begin_src conf
  bindsym $mod+Shift+$left move left
  bindsym $mod+Shift+$down move down
  bindsym $mod+Shift+$up move up
  bindsym $mod+Shift+$right move right

  bindsym $mod+Shift+Left move left
  bindsym $mod+Shift+Down move down
  bindsym $mod+Shift+Up move up
  bindsym $mod+Shift+Right move right
#+end_src

* Workspaces

Switch to workspace

#+begin_src conf
  bindsym $mod+1 workspace number 1
  bindsym $mod+2 workspace number 2
  bindsym $mod+3 workspace number 3
  bindsym $mod+4 workspace number 4
  bindsym $mod+5 workspace number 5
  bindsym $mod+6 workspace number 6
  bindsym $mod+7 workspace number 7
  bindsym $mod+8 workspace number 8
  bindsym $mod+9 workspace number 9
  bindsym $mod+0 workspace number 10
#+end_src

Move focused container to workspace

#+begin_src conf
  bindsym $mod+Shift+1 move container to workspace number 1
  bindsym $mod+Shift+2 move container to workspace number 2
  bindsym $mod+Shift+3 move container to workspace number 3
  bindsym $mod+Shift+4 move container to workspace number 4
  bindsym $mod+Shift+5 move container to workspace number 5
  bindsym $mod+Shift+6 move container to workspace number 6
  bindsym $mod+Shift+7 move container to workspace number 7
  bindsym $mod+Shift+8 move container to workspace number 8
  bindsym $mod+Shift+9 move container to workspace number 9
  bindsym $mod+Shift+0 move container to workspace number 10
#+end_src

* Layout stuff

#+begin_src conf
  # You can "split" the current object of your focus with
  # $mod+b or $mod+v, for horizontal and vertical splits
  # respectively.
  #bindsym $mod+b splith
  #bindsym $mod+v splitv

  # Switch the current container between different layout styles
  bindsym $mod+s layout stacking
  bindsym $mod+w layout tabbed
  bindsym $mod+e layout toggle split

  # Make the current focus fullscreen
  #bindsym $mod+f fullscreen

  # Toggle the current focus between tiling and floating mode
  bindsym $mod+Shift+space floating toggle

  # Swap focus between the tiling area and the floating area
  # bindsym $mod+space focus mode_toggle

  # Move focus to the parent container
  bindsym $mod+a focus parent
#+end_src

* Scratchpad

Sway has a "scratchpad", which is a bag of holding for windows. You can send windows there and get them back later.

#+begin_src conf
  bindsym $mod+Shift+minus move scratchpad
  bindsym $mod+minus scratchpad show
#+end_src

* Resizing containers

 left will shrink the containers width
 right will grow the containers width
 up will shrink the containers height
 down will grow the containers height

#+begin_src conf
  mode "resize" {
      bindsym $left resize shrink width 10px
      bindsym $down resize grow height 10px
      bindsym $up resize shrink height 10px
      bindsym $right resize grow width 10px

      bindsym Left resize shrink width 10px
      bindsym Down resize grow height 10px
      bindsym Up resize shrink height 10px
      bindsym Right resize grow width 10px

      bindsym Return mode "default"
      bindsym Escape mode "default"
  }

  bindsym $mod+r mode "resize"
#+end_src

* Bar

#+begin_src conf
  bar {
      swaybar_command waybar
  }

#+end_src

* Gaps

#+begin_src conf
  gaps outer 0
  default_border pixel 0
#+end_src

* Include

#+begin_src conf
  include /etc/sway/config.d/*
#+end_src
