#+title: Emacs Web
#+date: <2020-06-29 Mon>
#+hugo_base_dir: ~/Documents/Projects/mac-into-sh/
#+hugo_bundle: emacs-web
#+hugo_tags: emacs
#+export_file_name: index

* Introduction                                      :ignore:
I don't use Emacs to browse the web, although it can be done, and I guess people do. I do a few browser-related things in it though, including storing my bookmarks in an Org-mode file and such. Here's what I've changed.

* Set up browsing handlers                          :ignore:
Customizing the browse-url handlers is remarkably powerful. I don't use Emacs as a web browser much, but I do use a lot of links in Org-mode documents. If something isn't set here, it opens the URL in the default manner, which in my case is Safari ([[https://developer.apple.com/safari/technology-preview/][Technology Preview]]).

#+begin_src emacs-lisp
  (use-package browse-url
    :straight nil
    :custom
    (browse-url-handlers '(("wikipedia"   . eww )
                           ("youtu\\.?be" . actuator-browse-video)
                           ("twitch"      . actuator-browse-video))))
#+end_src

* Handle video urls                                 :ignore:
I want video links to be opened in MPV. This helps my battery life as well as my personal life because I don't have to visit YouTube. This requires [[https://mpv.io][MPV]] to be installed, which is best installed via [[http://brew.sh][Brew]] on macOS. I've tried to use [[https://nixos.org/download.html][Nix]], but it doesn't work well.

#+begin_src emacs-lisp
    (defun actuator-browse-video (url &rest _args)
      "Browse a URL with a dedicated video player.
  Avoids opening a browser window."
      (start-process "mpv" nil "mpv" url))
#+end_src

* Simple HTML renderer                              :ignore:
SHR is used to render all sorts of basic HTML in Emacs, including [[file:elfeed.org][Elfeed]] posts and Nov.el books. Normally it wraps at the page width, but that can be adjusted.

#+begin_src emacs-lisp
  (use-package shr
    :straight nil
    :custom
    (shr-width 75))
#+end_src

* Open links in background                          :ignore:
#+begin_src emacs-lisp
  (when (memq system-type '(darwin))
    (setq browse-url-browser-function 'browse-url-generic)
    (setq browse-url-generic-program "open")
    (setq browse-url-generic-args '("--background")))
#+end_src

* Metadata                       :noexport:blog:unpublished:
